server.port=3000

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/portpolio
spring.datasource.hikari.username=hellow
spring.datasource.hikari.password=hellow1234!

jwt.secret=jwtsecretkey

# Swagger Error
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.me.hello.backend=debug
logging.level.org=info

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

